from __future__ import annotations

from dataclasses import dataclass

from .content_provider import ProjectIdea


@dataclass(frozen=True)
class ProjectFile:
    path: str
    content: str


SUPPORTED_LANGUAGES = {"python", "javascript"}


def build_project_files(repository_name: str, idea: ProjectIdea, language: str) -> list[ProjectFile]:
    if language == "python":
        return _build_python_project(repository_name, idea)
    if language == "javascript":
        return _build_javascript_project(repository_name, idea)
    raise ValueError(f"Unsupported language: {language}")


def _readme(repository_name: str, idea: ProjectIdea, language: str) -> str:
    return f"""# {repository_name}

{idea.description}

## Tech Stack

- Language: {language}
- Generated by: GitHub Activity Automation System

## Getting Started

Review the starter source file, create a virtual environment or runtime setup for the language, and extend the project from there.

## Next Steps

- Add real domain logic.
- Add automated tests.
- Expand this README with usage examples.
"""


def _build_python_project(repository_name: str, idea: ProjectIdea) -> list[ProjectFile]:
    return [
        ProjectFile("README.md", _readme(repository_name, idea, "python")),
        ProjectFile(
            ".gitignore",
            "__pycache__/\n*.py[cod]\n.env\n.venv/\n.pytest_cache/\ndist/\nbuild/\n",
        ),
        ProjectFile(
            "src/main.py",
            '''"""Starter module generated by the Project Creator Agent."""


def main() -> None:
    print("Hello from this generated Python project.")


if __name__ == "__main__":
    main()
''',
        ),
        ProjectFile(
            "tests/test_smoke.py",
            '''from src.main import main


def test_main_runs(capsys):
    main()
    assert "Hello" in capsys.readouterr().out
''',
        ),
    ]


def _build_javascript_project(repository_name: str, idea: ProjectIdea) -> list[ProjectFile]:
    package_name = repository_name.lower()
    return [
        ProjectFile("README.md", _readme(repository_name, idea, "javascript")),
        ProjectFile(".gitignore", "node_modules/\n.env\ncoverage/\ndist/\n"),
        ProjectFile(
            "package.json",
            f'''{{
  "name": "{package_name}",
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "start": "node src/index.js"
  }}
}}
''',
        ),
        ProjectFile(
            "src/index.js",
            '''export function main() {
  console.log("Hello from this generated JavaScript project.");
}

main();
''',
        ),
    ]

